name: Generate Keystore (Sekali Saja)

on:
  workflow_dispatch:

jobs:
  buat_kunci:
    runs-on: ubuntu-latest
    steps:
      - name: Buat Keystore
        run: |
          keytool -genkeypair -v \
          -keystore keystore.jks \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -alias adixtream \
          -dname "CN=AdiXtream, OU=Dev, O=AdiXtream, L=ID, S=ID, C=ID" \
          -storepass 161105 \
          -keypass 161105
          
      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: keystore-file
          path: keystore.jks
