name: Buat Dokumentasi AdiXtream

on:
  workflow_dispatch: # Ini supaya muncul tombol "Run Workflow" manual

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil Kode (Checkout)
        uses: actions/checkout@v3

      - name: Siapkan Java (JDK 17)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Beri Izin Eksekusi Gradle
        run: chmod +x gradlew

      - name: Generate Dokumentasi (Dokka)
        run: ./gradlew dokkaHtml --no-daemon

      - name: Upload Hasil Dokumentasi
        uses: actions/upload-artifact@v3
        with:
          name: Dokumentasi-AdiXtream-HTML
          path: app/build/dokka/html/
