name: 1. GENERATE KUNCI BARU (JALANKAN SEKALI)

on:
  workflow_dispatch:

jobs:
  bikin_kunci:
    runs-on: ubuntu-latest
    steps:
      - name: Buat Keystore Baru
        run: |
          # Membuat file keystore baru dengan password '161105' dan alias 'adixtream'
          keytool -genkey -v -keystore app_keystore.jks \
            -alias adixtream \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass 161105 -keypass 161105 \
            -dname "CN=AdiXtream, OU=Dev, O=Adi, L=Indo, S=ID, C=ID"
            
      - name: Ubah ke Base64 (COPY KODE INI)
        run: |
          echo "ðŸ‘‡ðŸ‘‡ðŸ‘‡ COPY SEMUA KODE DI BAWAH INI (DARI MULAI HURUF M SAMPAI SIMBOL =) ðŸ‘‡ðŸ‘‡ðŸ‘‡"
          echo ""
          base64 -w 0 app_keystore.jks
          echo ""
          echo "ðŸ‘†ðŸ‘†ðŸ‘† SAMPAI SINI ðŸ‘†ðŸ‘†ðŸ‘†"
