name: Buat Dokumentasi AdiXtream

on:
  workflow_dispatch:

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Ambil Kode (Checkout)
        uses: actions/checkout@v4  # <-- Saya update jadi v4

      - name: Siapkan Java (JDK 17)
        uses: actions/setup-java@v4 # <-- Saya update jadi v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Beri Izin Eksekusi Gradle
        run: chmod +x gradlew

      - name: Generate Dokumentasi (Dokka)
        run: ./gradlew dokkaHtml --no-daemon

      - name: Upload Hasil Dokumentasi
        uses: actions/upload-artifact@v4 # <-- INI PERBAIKAN UTAMANYA (v3 -> v4)
        with:
          name: Dokumentasi-AdiXtream-HTML
          path: app/build/dokka/html/
